Added Dog model
2011JavaReact/project2-DT pull request #24
Opened 2020-12-19 02:16 UTC by gerardopg53

2020-12-19 14:47 UTC, corith requested changes

2020-12-19 14:47 UTC, corith commented on src/main/java/com/Barker/model/Dog.java
> +@Table(name = "planet")
planet?

2020-12-19 16:57 UTC, corith commented on src/main/java/com/Barker/model/Dog.java
> +import org.hibernate.annotations.Cache;
These dependencies need to be brought in through the pom.mxl

2020-12-21 04:33 UTC, gerardopg53 commented
Requested changes made. Changed table name, added dependencies to pom.xml, added the field sex to dog model, and fixed a typo on an import.

2020-12-21 21:48 UTC, gerardopg53 commented
bin folder deleted and added to .gitignore.

2020-12-21 23:10 UTC, corith approved these changes

2020-12-23 15:12 UTC, merged